sudo: required
services :
  - docker

before_install: 
  docker build -t fdesobry/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true fdesobry/frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "react-container"
  env: "ReactContainer-env" 
  bucket_name: "elasticbeanstalk-us-east-1-072819340530"
  bucket_path: "react-container"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"